apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: ghcr.io/kstacks-org/catalog-service:2e5cead077b3d4d373691dbff50161349c00beff
          ports:
            - containerPort: 41619
          envFrom:
            - configMapRef:
                name: catalog-config
            - secretRef:
                name: db-creds
            - secretRef:
                name: catalog-secret
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 41619
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 41619
            initialDelaySeconds: 10
            periodSeconds: 5
