apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: api-cors
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
      - "OPTIONS"
    accessControlAllowHeaders:
      - "Content-Type"
    accessControlAllowOriginList:
      - "https://kstacks.org"
      - "https://groups.kstacks.org"
    accessControlAllowCredentials: true    
