apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  SPRING_PROFILES_ACTIVE: prod
  APP_OAUTH2_REDIRECT_URI: https://kstacks.org/login-success
  APP_COOKIE_DOMAIN: kstacks.org
  JWT_ACCESS_TOKEN_PUBLIC_KEY: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7pscfM6VEu/5/0ENP3KTi+p4MNWwJGQvZHZYTiOthrLCYleLqILgItdNveCWY3jgDoZczw09pDJrqucjjLVriw==
  JWT_REFRESH_TOKEN_PUBLIC_KEY: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEp+h8BiYPtUs1MP0lPVSl7LZmAHtaqXgB/nHC/LiX5FquhIYYgCqbmUjbu5gl0RNYhPy0lqyIc7WhvmmDS1Ijew==
