apiVersion: apps/v1
kind: Deployment
metadata:
  name: groups-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: groups
  template:
    metadata:
      labels:
        app: groups
    spec:
      containers:
        - name: groups
          image: ghcr.io/KStacks-org/groups-service:master-255a40f
          ports:
            - containerPort: 6598
          envFrom:
            - configMapRef:
                name: groups-config
            - secretRef:
                name: db-creds
            - secretRef:
                name: groups-secret
          livenessProbe:
            httpGet:
              path: /groups/actuator/health/liveness
              port: 6598
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /groups/actuator/health/readiness
              port: 6598
            initialDelaySeconds: 10
            periodSeconds: 5
