---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-secret
  namespace: default
spec:
  encryptedData:
    DB_PASS: AgA0AAiHd/EFMf9QREdr07df0Iblp/CGeZjg7tC+IZQMGucEhr1vtXaMM1MGWLySdOm3C5mRh7uDYaU6OrGL/4JE7x8HLZeVNJdEBiN+0ZqjuxYCNAUHGzFfVLOGfs+Vkiesq6MBGjm2PdCIxOlDDvDDVljjvGJIBQfuJB0VB5SCMKWKh6wLXJGrh0cYBD3Gmg8QoqBQM0PjnNvzRVuha9u9cLJEsAjqphdL4+ig4d9L79SUxfKoV5XgeoEKIpIWVspNdruyUc8hFYdcKroNeUUlwz4SLwnAOXHL4fj9v3P5rvFrv0o2yg+hl9aB50L5aOI+e63RF7IE7P2reCBKqIyPs+6Z/bTn66Xkk6uvtJQszxmL1TFoXUdvuwoyCNr1TzbAZxrfrLV+v/VG/jAfqlSEIs/Gqv+C3V17S7Fgleh1o6yBn2mYtmrQj74z2HNreOyicJgTfbmiyMpp/z/2ALbBQzNCDTqfwvTR50oVT2j6KCu1dEHR2nYMiHeuojzvQcAVoscJg9pv1ygVcaw6yFr66BZAZkpjrudoo3RDQMu2928r1K2/vMSZ+4SqYFSR2aHEdUrqTGFDkdZ/QOdra8yC327pRWeBIhdXLFwCrx+caPw2f7kLZ5f43syis2BsOfDhEKRxT8kKgQ7gSYgtjV+GpTaQo8PDUdWhHPKfnr8hgHy6CHGl1wQg1Kb1/bldwkklbCPxwDMKgmRgV8owq9zgBsdwEt5RX1o=
    DB_USER: AgCvkLQC7K+QyWtmwJS3QJBRS04i2IAsLDFR+QQ3fqUQ1dOs4lC0kxhexHU1SgBoIOEJbzGnt5g+Ov7Pyjp1P8OI9erQjvigbxZsRXBQfRzMvNo9uhCMz1R6z3l4zsAbWZKXM2XfHj4imLrgMjP3gY4avE8KGLhyEf0H3liVqge8Ilj7+VOcVcq25RXEhaHKdetrvqUG3oEdahwOf85fh9F1/xecCde+PfdMd05iyt2m4o9vKmSmvcx/D86Km3D5dlIpdVG6GUnIHxhOWj2YOAYwC70/ahQzF4r/3iJjgWXLEabK7bVo7/rsERE27aqIKILjnF2ZGle7WukXfIsWekDGOt/lLG0xJHztc3Cs/52++kj9hvRXuTuaejNW31NhXMaAk+rmdMkd5MfGYhegAwpsCW+B8zKqK2Ub7Ljb/0ATkKoSJai+JJ7vMknaGgbu2p+1h+uQh91PiKkS0QEBbHKZnvGYH04L2h7A64+qy3wUVXmrpM2wk51Tiz+YHoKYV3PJJdBjPJHjGxPrB097nRXtOV9mzQBWYG3xA+rzujGP+OUjHwqxebVOwvxY2aVaf6JW93bfW0Ps6KpZm9rHAXgY/ztgtVgPpTSw77rd9jkBodVJPxyZgytuF62Lnua+HZi1S9PxEp6xkAiyMltgOi1uI2+XsqBgi4VpYMW2xVWZOcUwtVwdwVXc5apBEbQMDH9fNCguYj0=
  template:
    metadata:
      name: auth-secret
      namespace: default
    type: Opaque
