---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: groups-secret
  namespace: default
spec:
  encryptedData:
    DB_PASS: AgCdMqmcz085+g2Y3pG35t2ZTumIx0+BHpLpq2tzUKa+2ueWtASdh8cOyE0Bn/1EoKw3fdXtmYACtXFIOLftizi0rK8jfi6YVSBCTqG5hSrkWdULhR+2V1SE576tf9OBoX5D9D5JS513dMRipBnChV31TotSOAoaueyBiQyewTfyqAeCw/eq2Bbelk7l/esyyZ5RKySP+Vi/241Ad/0mmIwV66RIqmWF+fVYmOzX2nQXNAyE6R2FwjZ1D5mSJBmRNcA/gdOnCXl2RMzINWPTpbG91UDuwIUmPXe+co8Dqu0Sk58a1vwg5aClGU96sT5xmkz/UcpxRJJkOwt26EOITXIxFIYQVNwSriYghbYRTDvc40vSqTIHQUKfq9yYoJK+tGLKZ0qMwCNF3xQORem/oftehSOJeY6bOXy+us8B60l0gfidydJ5mUBCxSyf/i3yhAj4gTppkltRi5POGMDyVewq61XDpwP5OxW3rekjvdYVOtjBiMfMBJbb2pmmTIrDjJRuIfVxmmvQnyJNydCsf8scraEEro5NqYcSCI+z9A9Hgxizp6mvmlEorTi4/RCprTFbnHBi0kxgRXkrisSqNNk8F/c16NN/9e/K5NIjMtVxYkjF3WSxpCDe0tXalZZoR0fryBBEY5e0dWR++0KQma+Z+X/I9vXZqHHVKsXIkKvQCw92Wm7oU5msamS81w9uCdlZJG6R8D/A+EXFlZrlJ3TaC7aITODnkjw=
    DB_USER: AgAk4fLmljSzF9Vf/GR5B4O/mTohY53MtpP2DwbErLkWOMa0q20qo2lPFkbqDzzQ/kljIds0Ij6yuRSbdj5JQmxoYN922s7wgsMKbPfAuxkQXpLdy5ou7z0e00daqjNdHK1WnRMPjJ4qs/RhlGbxn19LbIhRD+54ZuBDdYiZEiNVUm9qpVcU9sjk9j9D1cP1SVOvEZq26JvIdo0X+zg2UXJC+wzahBMpugIVXTkN7N7kpzjTDX/cNxu/0qa2R9vd7tWNPU6krGXe4iSbGkLAdoii/aj+i3yvsI1nsen2scONR+5nhsiede8ohOS8X7JU1mhRcAue1hbBWcqmuZmtXIxLTAj+tNB5s7GNkw2XZm94KQHnCkOrqDyPBUCqUZNYAoGI4/XUUhTbe39FRRBX2y+Lrl4eSrfGhliLgtjXWTMi9aWzA8yrPo9dgLGcNGwBqAZN1iWjP72TqEsyMO+/llHOxkL9ZzeLmUrwKLsevq+VWpULQKMp8D+zdrSQ4jqqrxdzchLu2u4+6qacqNKry1lFMiovbxAiO21oLYW6IMro29AX0ImrEXc0EoxDFASJWMyuAG5zsspeYH2VQC3vHuyzo4gDumggLXjgXwUe3ugUhb2j2LWtmSwDWR8XYA1jyKUhJZSnIcK63gU2TUoDKkizTaQfr83EXbYEsHhdMunf4+KkRhTMV0709fjRk19OEE9NP7pLN0M=
  template:
    metadata:
      name: groups-secret
      namespace: default
    type: Opaque
