redis:
  fullnameOverride: redis
  architecture: standalone
  auth:
    enabled: false
  commonConfiguration: |-
    appendonly no
    save ""
    maxmemory 256mb
    maxmemory-policy allkeys-lru
  master:
    persistence:
      enabled: false
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 512Mi
