apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  SPRING_PROFILES_ACTIVE: prod
  DB_NAME: auth_db
  JWT_ACCESS_TOKEN_PUBLIC_KEY: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE7pscfM6VEu/5/0ENP3KTi+p4MNWwJGQvZHZYTiOthrLCYleLqILgItdNveCWY3jgDoZczw09pDJrqucjjLVriw==
  JWT_ACCESS_TOKEN_EXPIRATION: "300000" # 5 minutes
  JWT_REFRESH_TOKEN_PUBLIC_KEY: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEp+h8BiYPtUs1MP0lPVSl7LZmAHtaqXgB/nHC/LiX5FquhIYYgCqbmUjbu5gl0RNYhPy0lqyIc7WhvmmDS1Ijew==
  JWT_REFRESH_TOKEN_EXPIRATION: "604800000" # 7 days
  JWT_ISSUER: kstack
  APP_OAUTH2_REDIRECT_URI: https://kstacks.org/login-success
  APP_OAUTH2_HOSTED_DOMAIN: stu.kau.edu.sa
  SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE: profile,email
  SERVER_FORWARD_HEADERS_STRATEGY: framework
  APP_COOKIE_DOMAIN: kstacks.org  
