---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: genderize-secret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgCg8qae6iGuGoR69EUUVlgBy0DPbDMfkhtoVws3i3adxAoVzH1qIoScH8ekWQopu6h/Ae04RHmA7SPZs0VRv9pblws8QZjLxYGEgoEpSOEIKT7Btz7wau/OcFgv25qGF19MThlFlRu1ChNkV7zku5fSaGAmswDK+2jJmtas643DlkQGjWvoTJPTHyyKvslzlJE53aYQX/0skk9W0B2jm2Brcu5FZykWTlUC3DU5a1QQKLbYzCuRd6D0aC4UZdFMJPhz8Sb+cAe44+OgxCsFtvzOS5O1PHkhArgZIS21xoLw7hXJd30X2L7I7rge8020ni91TO33ubXazklM9QmSZBDQ4ZiP9e9s22xNMtBya3Po9Hj2csm+OUvJ0D6GQciFR8MYZesfJCp/8tmwUUlhOb5p0Q8UagOGD236ZQTKpA9MdKP4wGk16CiAdSisBokZdmLZbuuy2XR5s2QFjM3V46ag3CMSkDaMlI0+VXQFY391QHSfRluLTBjZ2z2sDic3+CdKayaCT7ExLAeIV+K1F5cfGuzpxnN6x1NjE5ngcsTFu0jSLCxTAViV59t/4omGlLqpunL0JwLEC7AwxqDLqcbzri7phH+byh/Flu6lBCqY0ccyZyUPIggHEQCcaV/8IYOEA6EkznUgoKOarmmPba+aKah8+i2cvbA1P0Za2xJaC3vYoope3J32JVH7k/yW2hVf2THn6KID4wGS4t09KbLGQnYRRwYobQ8=
    DB_USER: AgBbx43Ph+SFQByYMre5sx87ZYkvL8UIWygkJ+kYstUpyc1/fGX3dOJ/J3RD/6GLLRVQEhnc/DUZpxcm9jMsyLbNAYnXVONYaLVG7Dimvh7hJlwKE2hLQU7HTxY0M3BIc1B388cgZ9+S+44lcmSoxHqcKobeIBw7rj/eeDZy2NgbP6ibyGzBhf6HVsoaariZ/q3jOLS/AsYEzopyI6BmQRDcQj9PYC617ObBDv2ghL4KjKe9glCLpuMS8FajgPHjOEkVB8enq3B5F1IWmHMXaRixLfmPJS0IhgNO6Be8y+5tP8IFCj6dcJnME/oxzlNLBBR3zbgzAHEY29dJiKbOqFXzZOdMvNyksaeUOuUWucOwIieO9Hi/dmXrVVKa7AxKO/h25gBBd4R5ZYLNlz2DtuLw3IEseJ9oZRRKBbqBD0a0yIfGdnPDL/cLSyHsy6gTw2RBNNtBDsrYi+hMzXmyzotHsDWS3sThKSqB8W2NIKe6vasxRstcg1eTTcAnJnF3bZgjmkJO12m9ycZvRF+gIS9BKZRHvaLRbqmr+qowT8dUcovR6jsf41If1y+ArYzLOST0wtfTdSP8JeMLJqHfTVzxUFY5YZdrTPozGjQs0Fgy21D/PDIsnuTWOpq/XGgFdI9UhWWltR9VYuGCIeT555U75pAbXMpea7sr+qnt7FOY3T/gCmSIaSPDp+Q+kDD1G4g67CDM2FQJOk4=
  template:
    metadata:
      name: genderize-secret
      namespace: default
    type: Opaque
