---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: genderize-secret
  namespace: default
spec:
  encryptedData:
    DB_PASS: AgCPF6SJNje9qXuUTsYL/Y+YPvzexp2x6bZs+Qn1Y/DH7srd0dr1wdgLATanPZv5BgdbvXCBNVaPKXB9Fj8Vb4b4syLKzMxmATOxJWv1j3V6LsnI+f7omVM4C+TIm0tJM9Q4guqQVEgkwEK2VxUaATxZVlEbgCVmI5Fj2AGG7wVFNcSiyxRqIPvhc24jC62bLMgWwbpcQ+BitbKxfQ3RWEjKVWIZd89o2ZNuFwzuyXFSAT8B+bnq4wXJfn39mgAne63eptZlDsE/AhIfPP3MEvCNEWoCYaTdHSh5xuNhG5uIxtC6vWkkg3PVEfrjDNtMBcLsWEe9wYm6HY/IyzyouolHIPXgPsBcYCG45PvOfvfedhZXzxZIeu4WCmh8Aps0G/luUv6nHCujwWeoA9NR/DvJ1EpElSsmdHHCuObZcKvIukQ58ozDqNhtITXf8vjfk2njSriMbNno2D3YhwZ/5Zs+evNerdX2nix3WC9ZOrneUVkcjLhj0Z1uqFwJArOhrwbKdgtxMgxZpqekloVzLDHJcDUQsRbKG6H93aOIb+pZInVkGC4fFra3dWjcyXv4qbQgWKgYHp8UL1X0kxX3DsFJIFOqcY6P0Rnj+niW1ctvSxBtcpLGLq6NKaMMPu/IcCoCc7+PBMu6/OT4LCYZztttjLg+QjEUwU3/sjW3k+kCeLWQHuCt3FVtTd7gKEBg/EI1QgQlwHIxexicaPkhefbHOzs5daTZdp0=
    DB_USER: AgCqqeaRCJluk8+xs6DTOrj4vWABNcX/v7iNwZ3+sK5Q0U44lB8eATa4t1deIcPRwy3hYt38spMA/RCShSr4lCbAFbcMyGu3FNXebNOE/KLGZsTFkm1gfq+HeT4Fp2WX8XxLFpxDLgj+rtskr8kUGKPxvbnh0s8F8+5zHLjZngVkQsopy71TL6JxK6swaLavVRwjiLNWhLnik2go2amW5yu9qmNutoauIxslupPhKd0zhdpBzluVaXcD3/tA2HtLv+sl95zQwiqjbZdl9lD/vex0TpzIAHZPiQUB/Ol1tgYIAS2mqvDza7u4tp1781tWuvT9EpTVPEB+IYmAaQmfi/wWk6B3HeyXbidik9GYkbIzJmddt4uHiCcQLKHISZmdFA2gF2TPOct3eR7z/RVZXDMxxDeP+n+MuW54Ez+nBRPCdLHBoDcxSH+jJVNRGdTnjdz6M+wSZ69fJI5lkwq3+bKbIVFG+r9JbO3lU9553pKytxsdj6pk6umGb08pd1bxSYSwFanYRYIP5sf7lKDF7S/hjbrWidN+LdkFcxucFjRFZnnc9hhR0Bmj3PMQUtVN3DoeGsZCnS3oWFG3ubM6gtMfajlwsuveQqEwjPRCmH5JCloacgVJWJB0vJdlnhSKBQUSGi0jRrxa95yMGnmfl2uUuzvFWzERj79tVEyIZmp/01JCOFPbAllVClt+EqrXkwBnN4qRdCpDlqc=
  template:
    metadata:
      name: genderize-secret
      namespace: default
    type: Opaque
