apiVersion: v2
name: envoy-gateway
description: Envoy Gateway infrastructure component
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: gateway-helm
    alias: gateway
    version: 1.8.3
    repository: oci://docker.io/envoyproxy
  - name: gateway-crds-helm
    version: 1.8.3
    repository: oci://docker.io/envoyproxy
