# Values for envoy-gateway
gateway:
  deployment:
    replicas: 1
  crds:
    enabled: false
  config:
    envoyGateway:
      rateLimit:
        backend:
          type: Redis
          redis:
            url: redis-master.redis.svc.cluster.local:6379
        failClosed: false

gateway-crds-helm:
  crds:
    gatewayAPI:
      enabled: true
    envoyGateway:
      enabled: true
