apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-config
data:
  SPRING_PROFILES_ACTIVE: prod
  DB_NAME: catalog_db
  LOAD_DATA: "false"
  DB_DDL_AUTO: validate
  SERVER_SERVLET_CONTEXT_PATH: /catalog
  SERVER_FORWARD_HEADERS_STRATEGY: native
