---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-creds
  namespace: default
spec:
  encryptedData:
    DB_HOST: AgCD+WZUVw3GiqeyqZcj2Di/kF+2ZxMQ2ATHjujrsfOBd45oQIe//ZS4XdZJXeqRsf3pBWQ2cqouAaQ4ZeTGmCPF8vx+jyOCOpRMUBfZohsV73n16N69der5qeUmLLT+ScGeerOV8rGPbEUkXVf0q379z5IbzrWwKSGgVnBmVcHEWZPbQNw2R8/L+3qr6UMefJh5/m3HAIgAIwUYWkcKCZSpoG3sRrF6Y2i1byVuSVTP9XoqTYKpcnSHG0aOsMBhLaqf3S+nhHpVHNvNSElVZgrtrB4mTwB5SH510VZcJtVeYctiE7zieJPlSkNGateefZqlTZt+iPuJ25qoO/rwNfTfRgM5HBQgltQbE+LlRkGS73yARxq20WgkkS9RJXApvS9TGDHlxcxBmaCAZFvu524qTmXQAm5uMNsWVG6yTtq7t2V82mM8pIPL8e/QKB+H9FlcoGANgosyNHDbj+hzVZzDWIGxb7OiXvkCOxfcra8sF5BXcBti1dUnvQIJSyCpVNXYQUqe0+7w7BjHdzB0lJl7PtmSX5Gp2aNstb55rwK90Nkhxd1DIK8USG0f2Mh83v7h/HM+JVnRzPcGGpxnRqsz0sccvNGL8ZyFl2O6S9vqdjwWh0PgczD05n39z/t35P8CmhRIDGPPEwmsgboyxdA64bPnW/BRgEAqMIyMRtiixe7eTVvCtlISCViEYlDZiyhoPoWSye9hBuVXNIUEsFw=
    DB_PORT: AgBQLRu7TkeftEaI9iYYKRkanSIQJ/oDzelX7EbMUzuiH+ovfrL1Rntzf7gU0AJbI5Wi8udkIZStT4/NHPInJuLR4Ymq9Z2Ays1P2Vo/MdFkTwyz+XiwK6YahXA3Rp07gnRozHVawjNEKtDn5XkLJWfsVfs1K8ZvEriKfdMZICRtABPwplG5YNzUkdyT1LuPr69r1jtFQLeKNs4GHM8V6E49oimWzm2vErYnwdDdDBVuJVn3NAZaOPKg5ApqLU+3MvHH9cAP+p1Wj7uy83ZZuRdhh9TSv84iK239wB5EbjnprUNZJZzXyhMLktuZWLtF16+pA+V9fhonvMAJLiHwGxLsYpJvvleLvZCAWBZlcoZUnOqnqnokz/XzXI+vqGXy0zfKOTbxXZWQed1bKQ62k6xdtS/YSTlaDZGM3eQB+CXnFCxznKtKtqJnmiYcCKTLtXzJ0Ht1qHkJsA6N4GoXPSBKcc7uX3YKrjckV4h7o8FdfnZvmtjsya80SCawY7vBd6KTdj+eSAYhD7oJ0kutxBCmIXCQ4lmDL8E9Rb9MsZJUnqTrii7e9E7z7ZsQeSGn7yy15PF/n2Vh8pGiKxNW0hcPvJAIMHyo/ZYzkTwxrI0vGsKdLhBqFtXwRjIt29k9rlNp0ZsnPUmufU7Wt5BSOTNrr5GpYju/7XOw6aKUHjuoS2OpeuDfSX0BOZ1lHJvhXxGnXU6Q
  template:
    metadata:
      name: db-creds
      namespace: default
